package ControlleruserPhone;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.URL;
import java.util.Iterator;
import java.util.ResourceBundle;

import DAO_UserPhone.DaoTaiKhoan;
import ModelUserPhone.SharedData;
import ModelUserPhone.Taikhoan;
import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;

import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class HomeController  implements Initializable {
	@FXML
	private Button btnhome;
	@FXML
	private Button btnstore;
	@FXML
	private Button btncart;
	@FXML
	private Button btnsignout;
	@FXML
	private Pane bgcolor;
	private Socket socket=null;
	private PrintWriter out;
	private BufferedReader in;
    @FXML
    private Label name;

    private Taikhoan t;

    public HomeController(Taikhoan userModel) {
        this.t = userModel;
    }
	
    public HomeController() {
        
    }
	
	@FXML
	public void btnhomecart(MouseEvent event) {
		try {
		       FXMLLoader loader = new FXMLLoader(getClass().getResource("/ViewUserPhone./Cart.fxml"));
		       Parent cart = loader.load();
		       Scene Homecart = new Scene(cart);

		       Stage currentStage = (Stage) btncart.getScene().getWindow();
		       currentStage.setScene(Homecart);
		   } catch (IOException ex) {
		       ex.printStackTrace();
		   }

	
	}
	
	@FXML
	public void signoutt(MouseEvent event) {
		// TODO Autogenerated
        System.exit(0);

	}
	 @FXML
	    void storeclick(MouseEvent event) {
	
		 try {
			    
			    	       FXMLLoader loader = new FXMLLoader(getClass().getResource("/ViewUserPhone./Trangchu.fxml"));
			    	       Parent account = loader.load();
			    	       Scene account1 = new Scene(account);
		
			    	       Stage currentStage = (Stage) btnstore.getScene().getWindow();
			    	       currentStage.setScene(account1);
			    	       Platform.runLater(() -> {
			            	   t = new Taikhoan();
			            	   t.setUsername(name.getText());
			            	   ViewStoreController l = loader.getController();;
				             

			               });
			    	   } catch (IOException ex) {
			    	       ex.printStackTrace();
			    	   
			    	}
	    }
	 @FXML
	    void accountclick(MouseEvent event) {

	    
	    }
	 
	 public static void writeNumberToFile(int number, String filename) {
	        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filename))) {
	            writer.write(String.valueOf(number));
	        } catch (IOException e) {
	            e.printStackTrace();
	        }
	    }
	 public static int readNumberFromFile(String filename) {
	        try (BufferedReader reader = new BufferedReader(new FileReader(filename))) {
	            String line = reader.readLine();
	            return Integer.parseInt(line);
	        } catch (IOException e) {
	            e.printStackTrace();
	            return -1;
	        }
	    }
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		  Platform.runLater(() -> {
		Taikhoan currentUser = SharedData.getInstance().getCurrentUser();
        if (currentUser != null) {
            name.setText(currentUser.getUsername());
            

        }
	        });

	}
}
